#!/bin/bash

export REPOSITORIES=(
    "ui"
    "backend"
    "collector"
    "parser"
    "helm"
    "guard"
    "dependencies"
    "scripts"
    "cli"
    "deployment-operator"

    "ui-framework"
    "ui-components"
    "ui-middleware"
    "ui-alerts"
    "ui-dev-tools"
    "ui-properties"
    "ui-rule-engine" 
    "ui-search"
    "ui-time-machine"
    "ui-browser"
    "ui-validator-config"
    "ui-guard"
    "ui-worldvious"    
    "http-client"
    "helper-backend"
    "helpers"
    "helper-mysql"
    "helper-cache"
    "helper-easy-data-store" 
    "helper-redis"
    "helper-websocket-server"
    "helper-websocket-client"
    "worldvious-client"
    "entity-meta"
    "state-registry"
    "data-models"
    "agent-middleware"
    "helper-logic-processor"
    "kubik"
    "helper-rule-engine"
    "mock-data"


    "cli-releases"
    "homebrew-cli"

    "kubevious"
    "workspace"
    "rules-library"
    "demos"

    "portable"

    "homebrew-core"
)

# echo "REPOSITORIES: ${REPOSITORIES[@]}"
